### ISSUE TITLE
Replicating 20 Newsgroups

### ISSUE THREAD

**Issue by ZaydH** [cyber-meow/PUbiasedN#1]
I am trying to replicate the 20 newsgroups results in this paper.  If I am understanding the code correctly, the program is expecting the feature vectors in h5py files.  I do not see the code automatically generating these files or instructions how to create them ourselves.  Do you have any details you could share on this?

**Comment by cyber-meow** [comment]
Thank you very much for your interest. Related scripts and instructions have been updated.
